# the base image
FROM centos:7

# install commands
RUN yum -y update
RUN rpm -ivh http://dl.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm

# specify the port to be exposed
EXPOSE 8080


# run the application
#CMD["python", "-m SimpleHTTPServer"]

